services:
  fastapi:
    build: ./backend
    container_name: chatbot_fastapi
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
      - mongo
      - ollama
    environment:
      - QDRANT_URL=http://qdrant:6333
      - MONGO_URL=mongodb://mongo:27017
      - OLLAMA_URL=http://ollama:11434

  qdrant:
    image: qdrant/qdrant
    container_name: chatbot_qdrant
    ports:
      - "6333:6333"

  mongo:
    image: mongo
    container_name: chatbot_mongo
    ports:
      - "27017:27017"

  ollama:
    image: ollama/ollama
    container_name: chatbot_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: 